/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 ecommerce.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const mobile = window.innerWidth < 768;
  const { nodes, materials } = useGLTF('/ecommerce.glb')
  return (
    <group {...props} dispose={null} position={mobile?[0, -0.5, 0]:[0, -1, 0]} rotation={[0.5, -1.55, 0]} scale={mobile?0.9:1.2} >
      <group position={[-1.199, 0.096, 0]} rotation={[0, 0, -1.38]}>
        <mesh geometry={nodes.Object_10.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Object_11.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Object_4.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Object_7.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Object_9.geometry} material={materials['Material.006']} />
      </group>
      <mesh geometry={nodes.Object_13.geometry} material={materials['Material.008']} />
      <mesh geometry={nodes.Object_14.geometry} material={materials['Material.009']} />
      <mesh geometry={nodes.Object_15.geometry} material={materials['Material.009']} />
      <mesh geometry={nodes.Object_16.geometry} material={materials['Material.010']} />
      <mesh geometry={nodes.Object_17.geometry} material={materials['Material.011']} />
      <mesh geometry={nodes.Object_18.geometry} material={materials['Material.012']} />
      <mesh geometry={nodes.Object_19.geometry} material={materials['Material.014']} />
      <mesh geometry={nodes['Screenshot_2023-12-20_133340'].geometry} material={materials['Screenshot 2023-12-20 133340']} position={[-1.448, 1.545, 0.009]} rotation={[Math.PI / 2, 0.193, -Math.PI / 2]} scale={[2.175, 2.134, 2.134]} />
    </group>
  )
}

useGLTF.preload('/ecommerce.glb')
